### PR TITLE
[test] Add more tests for multi-memory

### PR DESCRIPTION
**Pull request by titzer**
This PR adds more tests for multiple memories under `test/core/multi-memory`.

Note that I found it convenient for testing to split out multiple files from the original core tests these were based on (e.g. `test0.wast`, `test1.wast`, etc). Willing to bikeshed the names or dump them back into the core directory if that is preferred.

### CODE REVIEW

**Review by rossberg — COMMENTED** [review]
Hm, I think we have two classes of tests wrt memory:

1. Those that are actually intended to test memory-related instructions or constructs.
2. Those that test other instructions, and only make spurious use of memory to perform the test.

It seems like this PR includes every main test that happened to mention a memory. But I wonder if it wouldn't be better to leave out the latter class of tests, since their relation to memory is mostly incidental, they don't test anything interesting about it, and their presence here is a bit confusing. WDYT?

**Comment by titzer** [comment]
> It seems like this PR includes every main test that happened to mention a memory. But I wonder if it wouldn't be better to leave out the latter class of tests, since their relation to memory is mostly incidental, they don't test anything interesting about it, and their presence here is a bit confusing. WDYT?

Some of the tests were to check thoroughly that the memory index space is being used properly; e.g. to use the `0th`, `1st`, `2nd` memory are used and not the other ones, particularly with imported memories.

I could go through and audit the tests again but I think the majority of them are worthwhile to keep. The spec tests are a somewhat inconsistent on how thorough their coverage is and I'd rather err on the side of redundancy than leave holes untested.

**Comment by rossberg** [comment]
I believe the second class consists of exactly those test files which are named after unrelated instructions (and which are hence surprising to see in the multi-memory dir). Agreed that test coverage is mixed, but that isn't necessarily helped by adding tangential tests. ;)

The primary reason why I'd prefer that is to maintain the organisational structure of the test suite, where (with a few historical exceptions) tests are named after the feature they test, which helps navigating it.

**Comment by titzer** [comment]
> I believe the second class consists of exactly those test files which are named after unrelated instructions (and which are hence surprising to see in the multi-memory dir). Agreed that test coverage is mixed, but that isn't necessarily helped by adding tangential tests. ;)
> 
> The primary reason why I'd prefer that is to maintain the organisational structure of the test suite, where (with a few historical exceptions) tests are named after the feature they test, which helps navigating it.

Ok, I see what you mean; there certainly were several tests where the result of a `memory.grow` was used as the "input" (only syntactically) to many other constructs. I'll go through those again.

**Comment by titzer** [comment]
I've removed most of the tests that had trivial incidental uses of memory.

**Review by rossberg — APPROVED** [review]
Cool, thanks!

**Pull request merged**
